import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useStyles } from '../styles/styles';

const Home: NextPage = () => {
  const classes = useStyles();
  const router = useRouter();

	return (
		<div className={classes.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<h1 className={classes.title} onClick={() => router.push('/login')}>
				Welcome to Next JS
			</h1>
		</div>
	);
};

export default Home;
